-- one8 FitLab — seed catalog (generated from backend/app/data/catalog.py)
-- Regenerate with: python backend/scripts/generate_seed.py

insert into products (id,name,tagline,price_inr,image_url,sport,surface,cushioning,support,width_class,fit_offset_mm) values ('one8-velocity-pro','one8 Velocity Pro','Race-day carbon-plated road racer.',12999,'/products/velocity-pro.svg','running','road','firm','neutral','standard',8.0) on conflict (id) do update set name=excluded.name, price_inr=excluded.price_inr;
insert into products (id,name,tagline,price_inr,image_url,sport,surface,cushioning,support,width_class,fit_offset_mm) values ('one8-glide-cushion','one8 Glide Cushion','Max-cushion daily trainer for easy miles.',9999,'/products/glide-cushion.svg','running','road','plush','cushion','wide',12.0) on conflict (id) do update set name=excluded.name, price_inr=excluded.price_inr;
insert into products (id,name,tagline,price_inr,image_url,sport,surface,cushioning,support,width_class,fit_offset_mm) values ('one8-terra-trail','one8 Terra Trail','Grippy, protective off-road companion.',11499,'/products/terra-trail.svg','running','trail','balanced','stability','wide',11.0) on conflict (id) do update set name=excluded.name, price_inr=excluded.price_inr;
insert into products (id,name,tagline,price_inr,image_url,sport,surface,cushioning,support,width_class,fit_offset_mm) values ('one8-forge-train','one8 Forge Trainer','Stable, flat platform for the gym floor.',8499,'/products/forge-train.svg','training','gym','firm','stability','standard',9.0) on conflict (id) do update set name=excluded.name, price_inr=excluded.price_inr;
insert into products (id,name,tagline,price_inr,image_url,sport,surface,cushioning,support,width_class,fit_offset_mm) values ('one8-court-ace','one8 Court Ace','Quick, locked-in multi-court shoe.',8999,'/products/court-ace.svg','court','mixed','balanced','neutral','narrow',7.0) on conflict (id) do update set name=excluded.name, price_inr=excluded.price_inr;
insert into products (id,name,tagline,price_inr,image_url,sport,surface,cushioning,support,width_class,fit_offset_mm) values ('one8-street-edit','one8 Street Edit','All-day lifestyle sneaker, athletic DNA.',6999,'/products/street-edit.svg','lifestyle','road','plush','neutral','standard',10.0) on conflict (id) do update set name=excluded.name, price_inr=excluded.price_inr;

insert into size_charts (product_id,size_label,length_mm) values ('one8-velocity-pro','UK 5',247.0) on conflict (product_id,size_label) do update set length_mm=excluded.length_mm;
insert into size_charts (product_id,size_label,length_mm) values ('one8-velocity-pro','UK 6',255.5) on conflict (product_id,size_label) do update set length_mm=excluded.length_mm;
insert into size_charts (product_id,size_label,length_mm) values ('one8-velocity-pro','UK 7',264.0) on conflict (product_id,size_label) do update set length_mm=excluded.length_mm;
insert into size_charts (product_id,size_label,length_mm) values ('one8-velocity-pro','UK 8',272.5) on conflict (product_id,size_label) do update set length_mm=excluded.length_mm;
insert into size_charts (product_id,size_label,length_mm) values ('one8-velocity-pro','UK 9',281.0) on conflict (product_id,size_label) do update set length_mm=excluded.length_mm;
insert into size_charts (product_id,size_label,length_mm) values ('one8-velocity-pro','UK 10',289.5) on conflict (product_id,size_label) do update set length_mm=excluded.length_mm;
insert into size_charts (product_id,size_label,length_mm) values ('one8-velocity-pro','UK 11',298.0) on conflict (product_id,size_label) do update set length_mm=excluded.length_mm;
insert into size_charts (product_id,size_label,length_mm) values ('one8-velocity-pro','UK 12',306.5) on conflict (product_id,size_label) do update set length_mm=excluded.length_mm;
insert into size_charts (product_id,size_label,length_mm) values ('one8-velocity-pro','UK 13',315.0) on conflict (product_id,size_label) do update set length_mm=excluded.length_mm;
insert into size_charts (product_id,size_label,length_mm) values ('one8-glide-cushion','UK 5',250.0) on conflict (product_id,size_label) do update set length_mm=excluded.length_mm;
insert into size_charts (product_id,size_label,length_mm) values ('one8-glide-cushion','UK 6',258.5) on conflict (product_id,size_label) do update set length_mm=excluded.length_mm;
insert into size_charts (product_id,size_label,length_mm) values ('one8-glide-cushion','UK 7',267.0) on conflict (product_id,size_label) do update set length_mm=excluded.length_mm;
insert into size_charts (product_id,size_label,length_mm) values ('one8-glide-cushion','UK 8',275.5) on conflict (product_id,size_label) do update set length_mm=excluded.length_mm;
insert into size_charts (product_id,size_label,length_mm) values ('one8-glide-cushion','UK 9',284.0) on conflict (product_id,size_label) do update set length_mm=excluded.length_mm;
insert into size_charts (product_id,size_label,length_mm) values ('one8-glide-cushion','UK 10',292.5) on conflict (product_id,size_label) do update set length_mm=excluded.length_mm;
insert into size_charts (product_id,size_label,length_mm) values ('one8-glide-cushion','UK 11',301.0) on conflict (product_id,size_label) do update set length_mm=excluded.length_mm;
insert into size_charts (product_id,size_label,length_mm) values ('one8-glide-cushion','UK 12',309.5) on conflict (product_id,size_label) do update set length_mm=excluded.length_mm;
insert into size_charts (product_id,size_label,length_mm) values ('one8-glide-cushion','UK 13',318.0) on conflict (product_id,size_label) do update set length_mm=excluded.length_mm;
insert into size_charts (product_id,size_label,length_mm) values ('one8-terra-trail','UK 5',249.0) on conflict (product_id,size_label) do update set length_mm=excluded.length_mm;
insert into size_charts (product_id,size_label,length_mm) values ('one8-terra-trail','UK 6',257.5) on conflict (product_id,size_label) do update set length_mm=excluded.length_mm;
insert into size_charts (product_id,size_label,length_mm) values ('one8-terra-trail','UK 7',266.0) on conflict (product_id,size_label) do update set length_mm=excluded.length_mm;
insert into size_charts (product_id,size_label,length_mm) values ('one8-terra-trail','UK 8',274.5) on conflict (product_id,size_label) do update set length_mm=excluded.length_mm;
insert into size_charts (product_id,size_label,length_mm) values ('one8-terra-trail','UK 9',283.0) on conflict (product_id,size_label) do update set length_mm=excluded.length_mm;
insert into size_charts (product_id,size_label,length_mm) values ('one8-terra-trail','UK 10',291.5) on conflict (product_id,size_label) do update set length_mm=excluded.length_mm;
insert into size_charts (product_id,size_label,length_mm) values ('one8-terra-trail','UK 11',300.0) on conflict (product_id,size_label) do update set length_mm=excluded.length_mm;
insert into size_charts (product_id,size_label,length_mm) values ('one8-terra-trail','UK 12',308.5) on conflict (product_id,size_label) do update set length_mm=excluded.length_mm;
insert into size_charts (product_id,size_label,length_mm) values ('one8-terra-trail','UK 13',317.0) on conflict (product_id,size_label) do update set length_mm=excluded.length_mm;
insert into size_charts (product_id,size_label,length_mm) values ('one8-forge-train','UK 5',246.0) on conflict (product_id,size_label) do update set length_mm=excluded.length_mm;
insert into size_charts (product_id,size_label,length_mm) values ('one8-forge-train','UK 6',254.5) on conflict (product_id,size_label) do update set length_mm=excluded.length_mm;
insert into size_charts (product_id,size_label,length_mm) values ('one8-forge-train','UK 7',263.0) on conflict (product_id,size_label) do update set length_mm=excluded.length_mm;
insert into size_charts (product_id,size_label,length_mm) values ('one8-forge-train','UK 8',271.5) on conflict (product_id,size_label) do update set length_mm=excluded.length_mm;
insert into size_charts (product_id,size_label,length_mm) values ('one8-forge-train','UK 9',280.0) on conflict (product_id,size_label) do update set length_mm=excluded.length_mm;
insert into size_charts (product_id,size_label,length_mm) values ('one8-forge-train','UK 10',288.5) on conflict (product_id,size_label) do update set length_mm=excluded.length_mm;
insert into size_charts (product_id,size_label,length_mm) values ('one8-forge-train','UK 11',297.0) on conflict (product_id,size_label) do update set length_mm=excluded.length_mm;
insert into size_charts (product_id,size_label,length_mm) values ('one8-forge-train','UK 12',305.5) on conflict (product_id,size_label) do update set length_mm=excluded.length_mm;
insert into size_charts (product_id,size_label,length_mm) values ('one8-forge-train','UK 13',314.0) on conflict (product_id,size_label) do update set length_mm=excluded.length_mm;
insert into size_charts (product_id,size_label,length_mm) values ('one8-court-ace','UK 5',245.0) on conflict (product_id,size_label) do update set length_mm=excluded.length_mm;
insert into size_charts (product_id,size_label,length_mm) values ('one8-court-ace','UK 6',253.5) on conflict (product_id,size_label) do update set length_mm=excluded.length_mm;
insert into size_charts (product_id,size_label,length_mm) values ('one8-court-ace','UK 7',262.0) on conflict (product_id,size_label) do update set length_mm=excluded.length_mm;
insert into size_charts (product_id,size_label,length_mm) values ('one8-court-ace','UK 8',270.5) on conflict (product_id,size_label) do update set length_mm=excluded.length_mm;
insert into size_charts (product_id,size_label,length_mm) values ('one8-court-ace','UK 9',279.0) on conflict (product_id,size_label) do update set length_mm=excluded.length_mm;
insert into size_charts (product_id,size_label,length_mm) values ('one8-court-ace','UK 10',287.5) on conflict (product_id,size_label) do update set length_mm=excluded.length_mm;
insert into size_charts (product_id,size_label,length_mm) values ('one8-court-ace','UK 11',296.0) on conflict (product_id,size_label) do update set length_mm=excluded.length_mm;
insert into size_charts (product_id,size_label,length_mm) values ('one8-court-ace','UK 12',304.5) on conflict (product_id,size_label) do update set length_mm=excluded.length_mm;
insert into size_charts (product_id,size_label,length_mm) values ('one8-court-ace','UK 13',313.0) on conflict (product_id,size_label) do update set length_mm=excluded.length_mm;
insert into size_charts (product_id,size_label,length_mm) values ('one8-street-edit','UK 5',248.0) on conflict (product_id,size_label) do update set length_mm=excluded.length_mm;
insert into size_charts (product_id,size_label,length_mm) values ('one8-street-edit','UK 6',256.5) on conflict (product_id,size_label) do update set length_mm=excluded.length_mm;
insert into size_charts (product_id,size_label,length_mm) values ('one8-street-edit','UK 7',265.0) on conflict (product_id,size_label) do update set length_mm=excluded.length_mm;
insert into size_charts (product_id,size_label,length_mm) values ('one8-street-edit','UK 8',273.5) on conflict (product_id,size_label) do update set length_mm=excluded.length_mm;
insert into size_charts (product_id,size_label,length_mm) values ('one8-street-edit','UK 9',282.0) on conflict (product_id,size_label) do update set length_mm=excluded.length_mm;
insert into size_charts (product_id,size_label,length_mm) values ('one8-street-edit','UK 10',290.5) on conflict (product_id,size_label) do update set length_mm=excluded.length_mm;
insert into size_charts (product_id,size_label,length_mm) values ('one8-street-edit','UK 11',299.0) on conflict (product_id,size_label) do update set length_mm=excluded.length_mm;
insert into size_charts (product_id,size_label,length_mm) values ('one8-street-edit','UK 12',307.5) on conflict (product_id,size_label) do update set length_mm=excluded.length_mm;
insert into size_charts (product_id,size_label,length_mm) values ('one8-street-edit','UK 13',316.0) on conflict (product_id,size_label) do update set length_mm=excluded.length_mm;
